version: "3"
services:
  vpn-pptp:
    image: lorf/vpn-pptp
    network_mode: host
    privileged: true
    #command:
    #  - pptpd
    #  - --fg
    #  - --debug
    #environment:
    #  - NETWORK=10.99.99.0/24
    #  - LOCALIP=10.99.99.1
    #  - IPRANGE=10.99.99.100-200
    #  - DNS1=8.8.8.8
    #  - DNS2=1.1.1.1
    volumes:
      - ./config:/config:ro
      - /dev/log:/dev/log
    restart: unless-stopped
