version: "3"
services:
  vpn-pptp:
    image: lorf/vpn-pptp
    network_mode: host
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.ip_forward: 1
    #command:
    #  - pptpd
    #  - --fg
    #  - --debug
    volumes:
      - ./chap-secrets:/etc/ppp/chap-secrets:ro
      - /dev/log:/dev/log
    restart: unless-stopped
