version: "3"
services:
  vpn-pptp:
    image: lorf/vpn-pptp
    network_mode: host
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.ip_forward: 1
    #command:
    #  - pptpd
    #  - --fg
    #  - --debug
    #environment:
    #  - NETWORK=10.99.99.0/24
    #  - LOCALIP=10.99.99.1
    #  - IPRANGE=10.99.99.100-200
    #  - DNS1=8.8.8.8
    #  - DNS2=1.1.1.1
    volumes:
      - ./chap-secrets:/etc/ppp/chap-secrets:ro
      - /dev/log:/dev/log
    restart: unless-stopped
